name: CI Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Say Hello
      run: echo "The pipeline is working!"
        
    - name: Lint with Flake8
      run: flake8 . --count --select=E1,F4 --show-source --statistics

